### ISSUE TITLE
ImportError: cannot import name 'BuiltInKeyEntry' from 'jax._src.tree_util'

### ISSUE THREAD

**Issue by Jemoka** [stanford-crfm/haliax#115]
Jax's merged PR (which is shipped now to production) https://github.com/jax-ml/jax/pull/24906 breaks https://github.com/stanford-crfm/haliax/blob/76b8f25af5bfff34fe58dbc67604d78577b91c17/src/haliax/quantization.py#L13 since `BuiltInKeyEntry` is no longer exposed as they moved much of their tree APIs to C++. 
Since this is only used for type annotations perhaps we can switch it to the public `KeyEntry` and it in theory wouldn't break anything.

Attached please find stack trace running

```
 python -m levanter.main.train_lm --config_path config/gpt2_small.yaml
```

on the config in the README.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/levanter/__init__.py", line 1, in <module>
    import levanter.checkpoint as checkpoint
  File "/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/levanter/checkpoint.py", line 26, in <module>
    import haliax.partitioning
  File "/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/haliax/__init__.py", line 14, in <module>
    import haliax.nn as nn
  File "/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/haliax/nn/__init__.py", line 36, in <module>
    from .linear import Linear
  File "/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/haliax/nn/linear.py", line 12, in <module>
    from ..quantization import DotGeneralOp
  File "/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/haliax/quantization.py", line 13, in <module>
    from jax._src.tree_util import BuiltInKeyEntry
ImportError: cannot import name 'BuiltInKeyEntry' from 'jax._src.tree_util' (/juice2/scr2/houjun/bigbert/.venv/lib/python3.11/site-packages/jax/_src/tree_util.py)
```

and `pip freeze`: https://pastebin.com/raw/z2hRYaE5

**Comment by Jemoka** [comment]
closed by https://github.com/stanford-crfm/haliax/commit/81bbb7887704eeb0e016a47508ea8963f38686be
